### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Jack12xl** [Jack12xl/myFluid#2]
- [x] Transform
- [x] SDF
- [ ] Euler fluid solid coupling

- [x] refractor grid

- [x] add staggered grid

- [x] SDF rasterize to world space

**Comment by Jack12xl** [comment]
- [ ] numerical benchmark camparisons for different Projection methods

**Comment by Jack12xl** [comment]
- [x] Add cache read

**Comment by Jack12xl** [comment]
- [x] Abstract emitter

**Comment by Jack12xl** [comment]
- [x] Support different grid size with same screen size

**Comment by Jack12xl** [comment]
- [x] abstract renderer

**Comment by Jack12xl** [comment]
Make it a real smoke simulator:

- [x] Add temperature and advect

- [x] Add bouyancy force

**Comment by Jack12xl** [comment]
- [ ] Refactor the solver called pipeline. Make it easier to use.
